-- MySQL Script generated by MySQL Workbench
-- Tue May  3 01:39:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`football_ligue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`football_ligue` (
  `id` INT NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`championship` (
  `id` INT NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `football_ligue_id` INT NOT NULL,
  PRIMARY KEY (`id`, `football_ligue_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_championship_football_ligue1_idx` (`football_ligue_id` ASC) VISIBLE,
  CONSTRAINT `fk_championship_football_ligue1`
    FOREIGN KEY (`football_ligue_id`)
    REFERENCES `mydb`.`football_ligue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `id_player` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id_player`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`player_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player_match` (
  `id_player` INT NOT NULL,
  `id_match` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `shirt_number` INT NOT NULL,
  `banns` INT NULL,
  `goals` INT NULL,
  `player_id_player` INT NOT NULL,
  PRIMARY KEY (`id_player`, `id_match`, `player_id_player`),
  INDEX `fk_player_match_player1_idx` (`player_id_player` ASC) VISIBLE,
  CONSTRAINT `fk_player_match_player1`
    FOREIGN KEY (`player_id_player`)
    REFERENCES `mydb`.`player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fans` (
  `id_fan` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`id_fan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`referee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`referee` (
  `id_referee` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthday` DATE NULL,
  PRIMARY KEY (`id_referee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tecnichal_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnichal_manager` (
  `id_tecnichal_manager` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`id_tecnichal_manager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`football_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`football_team` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tecnichal_manager_id_tecnichal_manager` INT NOT NULL,
  PRIMARY KEY (`id`, `tecnichal_manager_id_tecnichal_manager`),
  INDEX `fk_football_team_tecnichal_manager1_idx` (`tecnichal_manager_id_tecnichal_manager` ASC) VISIBLE,
  CONSTRAINT `fk_football_team_tecnichal_manager1`
    FOREIGN KEY (`tecnichal_manager_id_tecnichal_manager`)
    REFERENCES `mydb`.`tecnichal_manager` (`id_tecnichal_manager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stadium` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matchs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matchs` (
  `id` INT NOT NULL,
  `q_goals` INT NULL,
  `result` INT NOT NULL,
  `player_match_id_player` INT NOT NULL,
  `player_match_id_match` INT NOT NULL,
  `player_match_player_id_player` INT NOT NULL,
  `fans_id_fan` INT NOT NULL,
  `championship_id` INT NOT NULL,
  `championship_football_ligue_id` INT NOT NULL,
  `referee_id_referee` INT NOT NULL,
  `football_ligue_id` INT NOT NULL,
  `football_team_id` INT NOT NULL,
  `football_team_tecnichal_manager_id_tecnichal_manager` INT NOT NULL,
  `stadium_id` INT NOT NULL,
  PRIMARY KEY (`id`, `player_match_id_player`, `player_match_id_match`, `player_match_player_id_player`, `fans_id_fan`, `championship_id`, `championship_football_ligue_id`, `referee_id_referee`, `stadium_id`),
  INDEX `fk_matchs_player_match1_idx` (`player_match_id_player` ASC, `player_match_id_match` ASC, `player_match_player_id_player` ASC) VISIBLE,
  INDEX `fk_matchs_fans1_idx` (`fans_id_fan` ASC) VISIBLE,
  INDEX `fk_matchs_championship1_idx` (`championship_id` ASC, `championship_football_ligue_id` ASC) VISIBLE,
  INDEX `fk_matchs_referee1_idx` (`referee_id_referee` ASC) VISIBLE,
  INDEX `fk_matchs_football_ligue1_idx` (`football_ligue_id` ASC) VISIBLE,
  INDEX `fk_matchs_football_team1_idx` (`football_team_id` ASC, `football_team_tecnichal_manager_id_tecnichal_manager` ASC) VISIBLE,
  INDEX `fk_matchs_stadium1_idx` (`stadium_id` ASC) VISIBLE,
  CONSTRAINT `fk_matchs_player_match1`
    FOREIGN KEY (`player_match_id_player` , `player_match_id_match` , `player_match_player_id_player`)
    REFERENCES `mydb`.`player_match` (`id_player` , `id_match` , `player_id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_fans1`
    FOREIGN KEY (`fans_id_fan`)
    REFERENCES `mydb`.`fans` (`id_fan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_championship1`
    FOREIGN KEY (`championship_id` , `championship_football_ligue_id`)
    REFERENCES `mydb`.`championship` (`id` , `football_ligue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_referee1`
    FOREIGN KEY (`referee_id_referee`)
    REFERENCES `mydb`.`referee` (`id_referee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_football_ligue1`
    FOREIGN KEY (`football_ligue_id`)
    REFERENCES `mydb`.`football_ligue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_football_team1`
    FOREIGN KEY (`football_team_id` , `football_team_tecnichal_manager_id_tecnichal_manager`)
    REFERENCES `mydb`.`football_team` (`id` , `tecnichal_manager_id_tecnichal_manager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matchs_stadium1`
    FOREIGN KEY (`stadium_id`)
    REFERENCES `mydb`.`stadium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`captain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`captain` (
  `id_captain` INT NOT NULL,
  `football_team_id` INT NOT NULL,
  `player_id_player` INT NOT NULL,
  PRIMARY KEY (`id_captain`),
  INDEX `fk_captain_football_team1_idx` (`football_team_id` ASC) VISIBLE,
  INDEX `fk_captain_player1_idx` (`player_id_player` ASC) VISIBLE,
  CONSTRAINT `fk_captain_football_team1`
    FOREIGN KEY (`football_team_id`)
    REFERENCES `mydb`.`football_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_captain_player1`
    FOREIGN KEY (`player_id_player`)
    REFERENCES `mydb`.`player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team_has_stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team_has_stadium` (
  `id_team` INT NOT NULL,
  `id_stadium` INT NOT NULL,
  `stadium_id` INT NOT NULL,
  `football_team_id` INT NOT NULL,
  PRIMARY KEY (`id_team`, `id_stadium`, `stadium_id`, `football_team_id`),
  INDEX `fk_team_has_stadium_stadium1_idx` (`stadium_id` ASC) VISIBLE,
  INDEX `fk_team_has_stadium_football_team1_idx` (`football_team_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_stadium_stadium1`
    FOREIGN KEY (`stadium_id`)
    REFERENCES `mydb`.`stadium` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_stadium_football_team1`
    FOREIGN KEY (`football_team_id`)
    REFERENCES `mydb`.`football_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
